### ISSUE TITLE
Provide releases using github?

### ISSUE THREAD

**Issue by wolfeidau** [unifio/packer-provisioner-serverspec#3]
Looks like a great plugin, maybe a brew tap + github releases would be cool to let others consume it easier.

https://github.com/progrium/gh-release is what I normally use.

Paired with something like this https://github.com/wolfeidau/homebrew-taps/blob/master/unicreds.rb

Cheers

**Comment by blakeneyops** [comment]
Hi Mark,

Thanks for the feedback. I will definitely get that done and update you here when it is. It is my intention to open a PR with HashiCorp for inclusion in the Packer core as well.

**Comment by nwalke** [comment]
@blakeneyops Do you still have plans to do that ^?

**Comment by disaac** [comment]
@nwalke We have begun using goreleaser to make the binaries available via github release tags. A binary for many architectures is generated including macos.

Regarding the inclusion in the packer core are still looking into this and have created [issue #12](https://github.com/unifio/packer-provisioner-serverspec/issues/12) to track this.
