### ISSUE TITLE
Will this work with the amazon-ebs builder?

### ISSUE THREAD

**Issue by nullpunkt5** [unifio/packer-provisioner-serverspec#5]
Using the amazon-ebs to create AMIs - is this plugin able to run serverspec in said building machine? The whole procedure is run via an ec2-hosted Jenkins so it's ideal to have it all automated within the pipeline, by simply adding the serverspec provisioner to the packer json.

**Comment by disaac** [comment]
Yes assuming the dependencies are present on the jenkins build machine or a container with all of the dependencies present is used during the pipeline.
